import unittest

from appium import webdriver
import pytest
from time import sleep

from attr import field

from AppiumFrameWork1.pages.LoginPage import LoginPage
from AppiumFrameWork1.pages.OrderPage import orderPage

import random

delivery_fee = ['40', '30', '50', '60', '70', '80', '90', '100']


class OrdersPage(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Remote(command_executor="http://127.0.0.1:4723/wd/hub",
                                       desired_capabilities=
                                       {
                                           "platformName": "Android",
                                           "platformVersion": "9",
                                           "deviceName": "emulator-5554",
                                           "automationName": "uiautomator2",
                                           "app": "C:/Users/clinton/Downloads/app-prod-debug.apk",
                                           "newCommandTimeout": 600,
                                           "launchTimeout": "90000",
                                           "adbExecTimeout": "30000",
                                           "autoGrantPermissions": "true"
                                       })

    def test_order_details_page(self):
        self.driver.launch_app()
        sleep(2)
        get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        get_started_button.click()
        sleep(1)
        continue_with_email_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        continue_with_email_button.click()
        sleep(1)
        email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
        email_address_textbox.send_keys("cojeret739@kuruapp.com")
        sleep(1)
        continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        continue_button.click()
        sleep(2)
        password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
        password_textbox.send_keys("dukaanauto")
        sleep(2)
        enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        enter_password_button.click()
        sleep(5)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(2)
        details_button = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Details")')
        details_button.click()
        sleep(2)
        assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Home")')

    # def test_accept_order(self):
    #     self.driver.launch_app()
    #     sleep(2)
    #     get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
    #     get_started_button.click()
    #     sleep(1)
    #     continue_with_email_button = self.driver.find_element_by_android_uiautomator(
    #         'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
    #     continue_with_email_button.click()
    #     sleep(1)
    #     email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
    #     email_address_textbox.send_keys("cojeret739@kuruapp.com")
    #     sleep(1)
    #     continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
    #     continue_button.click()
    #     sleep(2)
    #     password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
    #     password_textbox.send_keys("dukaanauto")
    #     sleep(2)
    #     enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
    #     enter_password_button.click()
    #     sleep(3)
    #     orders_icon = self.driver.find_element_by_android_uiautomator(
    #         'new UiSelector().className("android.widget.TextView").text("Orders")')
    #     orders_icon.click()
    #     sleep(2)
    #     filter_pending = self.driver.find_element_by_id("com.dukaan.app:id/status_pending")
    #     filter_pending.click()
    #     sleep(2)
    #     pending_text = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Pending")')
    #     pending_text.click()
    #     sleep(2)
    #     accept_button = self.driver.find_element_by_id("com.dukaan.app:id/primaryButton")
    #     accept_button.click()
    #     sleep(2)
    #     choose_delivery_time = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("3-5 days")')
    #     choose_delivery_time.click()
    #     sleep(2)
    #     accept_order_button = self.driver.find_element_by_id("com.dukaan.app:id/consentActionTV")
    #     accept_order_button.click()
    #     sleep(3)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Accepted")')
    #
    # def test_ship_order(self):
    #     self.driver.launch_app()
    #     sleep(10)
    #     orders_icon = self.driver.find_element_by_id("com.dukaan.app:id/orders_iv")
    #     orders_icon.click()
    #     sleep(2)
    #     filter_accepted = self.driver.find_element_by_id("com.dukaan.app:id/status_accepted")
    #     filter_accepted.click()
    #     sleep(1)
    #     accepted_text = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Accepted")')
    #     accepted_text.click()
    #     sleep(2)
    #     ship_order_button = self.driver.find_element_by_id("com.dukaan.app:id/primaryButton")
    #     ship_order_button.click()
    #     sleep(2)
    #     confirm_ship_button = self.driver.find_element_by_id("com.dukaan.app:id/consentActionTV")
    #     confirm_ship_button.click()
    #     sleep(5)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Shipped")')
    #
    # def test_order_delivered_status(self):
    #     self.driver.launch_app()
    #     sleep(10)
    #     orders_icon = self.driver.find_element_by_id("com.dukaan.app:id/orders_iv")
    #     orders_icon.click()
    #     sleep(2)
    #     self.driver.swipe(1034, 283, 50, 250, 400)
    #     filter_shipped = self.driver.find_element_by_id("com.dukaan.app:id/status_shipped")
    #     filter_shipped.click()
    #     sleep(2)
    #     shipped_text = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Shipped")')
    #     shipped_text.click()
    #     sleep(2)
    #     delivered_button = self.driver.find_element_by_id("com.dukaan.app:id/primaryButton")
    #     delivered_button.click()
    #     sleep(2)
    #     confirm_delivery = self.driver.find_element_by_id("com.dukaan.app:id/consentActionTV")
    #     confirm_delivery.click()
    #     sleep(2)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Delivered")')
    #
    # def test_reject_order(self):
    #     self.driver.launch_app()
    #     sleep(10)
    #     orders_icon = self.driver.find_element_by_id("com.dukaan.app:id/orders_iv")
    #     orders_icon.click()
    #     sleep(2)
    #     filter_pending = self.driver.find_element_by_id("com.dukaan.app:id/status_pending")
    #     filter_pending.click()
    #     sleep(2)
    #     pending_text = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Pending")')
    #     pending_text.click()
    #     sleep(2)
    #     reject_order_button = self.driver.find_element_by_id("com.dukaan.app:id/secondaryButton")
    #     reject_order_button.click()
    #     sleep(2)
    #     confirm_reject_button = self.driver.find_element_by_id("com.dukaan.app:id/consentActionTV")
    #     confirm_reject_button.click()
    #     sleep(2)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Rejected")')
    #
    # def test_cancel_order(self):
    #     self.driver.launch_app()
    #     sleep(10)
    #     orders_icon = self.driver.find_element_by_id("com.dukaan.app:id/orders_iv")
    #     orders_icon.click()
    #     sleep(2)
    #     filter_accepted = self.driver.find_element_by_id("com.dukaan.app:id/status_accepted")
    #     filter_accepted.click()
    #     sleep(1)
    #     accepted_text = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Accepted")')
    #     accepted_text.click()
    #     sleep(3)
    #     cancel_button = self.driver.find_element_by_id("com.dukaan.app:id/secondaryButton")
    #     cancel_button.click()
    #     sleep(2)
    #     confirm_cancel_order = self.driver.find_element_by_id("com.dukaan.app:id/consentActionTV")
    #     confirm_cancel_order.click()
    #     sleep(3)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Cancelled")')
    #
    # def test_order_page_filters(self):
    #     self.driver.launch_app()
    #     sleep(10)
    #     orders_icon = self.driver.find_element_by_id("com.dukaan.app:id/orders_iv")
    #     orders_icon.click()
    #     filter_pending = self.driver.find_element_by_id("com.dukaan.app:id/status_pending")
    #     filter_pending.click()
    #     sleep(2)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Pending")')
    #     filter_accepted = self.driver.find_element_by_id("com.dukaan.app:id/status_accepted")
    #     filter_accepted.click()
    #     sleep(2)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Accepted")')
    #     filter_rejected = self.driver.find_element_by_id("com.dukaan.app:id/status_rejected")
    #     filter_rejected.click()
    #     sleep(2)
    #     self.driver.swipe(1050, 250, 500, 250, 400)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Rejected")')
    #     filter_modified = self.driver.find_element_by_id("com.dukaan.app:id/status_modified")
    #     filter_modified.click()
    #     sleep(2)
    #     assert self.driver.find_element_by_android_uiautomator(
    #         'new UiSelector().className("android.widget.TextView").text("Modified")')
    #     sleep(1)
    #     filter_shipped = self.driver.find_element_by_id("com.dukaan.app:id/status_shipped")
    #     filter_shipped.click()
    #     sleep(2)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Shipped")')
    #     sleep(1)
    #     self.driver.swipe(1050, 250, 50, 250, 400)
    #     sleep(1)
    #     filter_cancelled = self.driver.find_element_by_id("com.dukaan.app:id/status_cancelled")
    #     filter_cancelled.click()
    #     sleep(2)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Cancelled")')
    #     sleep(1)
    #     filter_delivered = self.driver.find_element_by_id("com.dukaan.app:id/status_delivered")
    #     filter_delivered.click()
    #     sleep(2)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Served")')

    def test_download_reports(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(3)
        download_report_button = self.driver.find_element_by_id("com.dukaan.app:id/downloadReportFAB")
        download_report_button.click()
        sleep(3)
        select_pdf = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("PDF")')
        select_pdf.click()
        sleep(8)
        assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Report successfully downloaded")')

    def test_order_search_by_mobile_number(self):
        self.driver.launch_app()
        sleep(2)
        get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        get_started_button.click()
        sleep(1)
        continue_with_email_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        continue_with_email_button.click()
        sleep(1)
        email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
        email_address_textbox.send_keys("cojeret739@kuruapp.com")
        sleep(1)
        continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        continue_button.click()
        sleep(2)
        password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
        password_textbox.send_keys("dukaanauto")
        sleep(2)
        enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        enter_password_button.click()
        sleep(5)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(2)
        search_icon = self.driver.find_element_by_id("com.dukaan.app:id/search")
        search_icon.click()
        sleep(1)
        search_textbox = self.driver.find_element_by_id("com.dukaan.app:id/search_src_text")
        search_textbox.send_keys("7012799237")
        sleep(2)
        details_button = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Details")')
        details_button.click()
        sleep(2)
        assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("7012799237")')

    def test_order_search_by_name(self):
        self.driver.launch_app()
        sleep(2)
        get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        get_started_button.click()
        sleep(1)
        continue_with_email_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        continue_with_email_button.click()
        sleep(1)
        email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
        email_address_textbox.send_keys("cojeret739@kuruapp.com")
        sleep(1)
        continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        continue_button.click()
        sleep(2)
        password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
        password_textbox.send_keys("dukaanauto")
        sleep(2)
        enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        enter_password_button.click()
        sleep(5)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(3)
        search_icon = self.driver.find_element_by_id("com.dukaan.app:id/search")
        search_icon.click()
        sleep(1)
        search_textbox = self.driver.find_element_by_id("com.dukaan.app:id/search_src_text")
        search_textbox.send_keys("Test")
        sleep(2)
        details_button = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Details")')
        details_button.click()
        sleep(2)
        assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Test")')

    # def test_orders_flow(self):
    #     self.driver.launch_app()
    #     sleep(7)
    #     orders_icon = self.driver.find_element_by_id("com.dukaan.app:id/orders_iv")
    #     orders_icon.click()
    #     sleep(2)
    #     filter_pending = self.driver.find_element_by_id("com.dukaan.app:id/status_pending")
    #     filter_pending.click()
    #     sleep(2)
    #     order_details = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Details")')
    #     order_details.click()
    #     sleep(3)
    #     accept_button = self.driver.find_element_by_id("com.dukaan.app:id/primaryButton")
    #     accept_button.click()
    #     sleep(3)
    #     choose_time = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("3-5 days")')
    #     choose_time.click()
    #     sleep(2)
    #     confirm_accept = self.driver.find_element_by_id("com.dukaan.app:id/consentActionTV")
    #     confirm_accept.click()
    #     sleep(4)
    #     ship_order = self.driver.find_element_by_id("com.dukaan.app:id/primaryButton")
    #     ship_order.click()
    #     sleep(2)
    #     confirm_ship = self.driver.find_element_by_id("com.dukaan.app:id/consentActionTV")
    #     confirm_ship.click()
    #     sleep(3)
    #     delivered_button = self.driver.find_element_by_id("com.dukaan.app:id/primaryButton")
    #     delivered_button.click()
    #     sleep(2)
    #     confirm_delivery = self.driver.find_element_by_id("com.dukaan.app:id/consentActionTV")
    #     confirm_delivery.click()
    #     sleep(4)
    #     assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Delivered")')

    def test_edit_delivery_fee(self):
        random_fee_amount = (random.choice(delivery_fee))
        self.driver.launch_app()
        sleep(2)
        get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        get_started_button.click()
        sleep(1)
        continue_with_email_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        continue_with_email_button.click()
        sleep(1)
        email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
        email_address_textbox.send_keys("cojeret739@kuruapp.com")
        sleep(1)
        continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        continue_button.click()
        sleep(2)
        password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
        password_textbox.send_keys("dukaanauto")
        sleep(2)
        enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        enter_password_button.click()
        sleep(5)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(4)
        order_select = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Pending")')
        order_select.click()
        sleep(2)
        edit_order_button = self.driver.find_element_by_id("com.dukaan.app:id/editOrderTV")
        edit_order_button.click()
        sleep(1)
        edit_delivery_fee_button = self.driver.find_element_by_id("com.dukaan.app:id/editFeeTV")
        edit_delivery_fee_button.click()
        sleep(1)
        delivery_fee_textbox = self.driver.find_element_by_id("com.dukaan.app:id/deliveryPriceET")
        delivery_fee_textbox.send_keys(random_fee_amount)
        change_button = self.driver.find_element_by_id("com.dukaan.app:id/confirmButton")
        change_button.click()
        sleep(2)
        request_confirmation_button = self.driver.find_element_by_id("com.dukaan.app:id/requestConfirmationButton")
        request_confirmation_button.click()
        sleep(2)
        assert self.driver.find_element_by_id("com.dukaan.app:id/closeButton")
        close_button = self.driver.find_element_by_id("com.dukaan.app:id/closeButton")
        close_button.click()
        sleep(2)
        assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Modified")')

    def test_orders_page_range_filters(self):
        self.driver.launch_app()
        sleep(2)
        get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        get_started_button.click()
        sleep(1)
        continue_with_email_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        continue_with_email_button.click()
        sleep(1)
        email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
        email_address_textbox.send_keys("cojeret739@kuruapp.com")
        sleep(1)
        continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        continue_button.click()
        sleep(2)
        password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
        password_textbox.send_keys("dukaanauto")
        sleep(2)
        enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        enter_password_button.click()
        sleep(5)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(3)
        filter_dropdown_button = self.driver.find_element_by_id("com.dukaan.app:id/filterSelectorTV")
        filter_dropdown_button.click()
        sleep(1)
        filter_today = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Today")')
        filter_today.click()
        sleep(3)
        close_add = self.driver.find_element_by_id("com.dukaan.app:id/ivClose")
        close_add.click()
        sleep(5)
        assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Today")')
        filter_dropdown_button.click()
        sleep(2)
        filter_yesterday = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Yesterday")')
        filter_yesterday.click()
        sleep(1)
        assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("Yesterday")')
        filter_dropdown_button.click()
        sleep(1)
        filter_this_week = self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("This Week")')
        filter_this_week.click()
        sleep(1)
        assert self.driver.find_element_by_android_uiautomator('new UiSelector().className("android.widget.TextView").text("This Week")')
        filter_dropdown_button.click()
        sleep(1)
        filter_this_month = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("This Month")')
        filter_this_month.click()
        sleep(1)
        assert self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("This Month")')
        filter_dropdown_button.click()
        sleep(1)
        filter_life_time = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Life Time")')
        filter_life_time.click()
        sleep(1)
        assert self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Life Time")')
        filter_dropdown_button.click()
        sleep(1)
        filter_custom_range = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Custom range")')
        filter_custom_range.click()
        sleep(1)
        left_navigation_button = self.driver.find_element_by_id("com.dukaan.app:id/imgVNavLeft")
        left_navigation_button.click()
        sleep(1)
        start_date_select = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("1")')
        start_date_select.click()
        end_date_select = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("28")')
        end_date_select.click()
        apply_button = self.driver.find_element_by_id("com.dukaan.app:id/tvBtnApplyCalendarFilter")
        apply_button.click()
        sleep(3)
        assert self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("01/02/22 - 28/02/22")')

    def test_order_id_matching(self):
        self.driver.launch_app()
        sleep(2)
        get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        get_started_button.click()
        sleep(1)
        continue_with_email_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        continue_with_email_button.click()
        sleep(1)
        email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
        email_address_textbox.send_keys("cojeret739@kuruapp.com")
        sleep(1)
        continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        continue_button.click()
        sleep(2)
        password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
        password_textbox.send_keys("dukaanauto")
        sleep(2)
        enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        enter_password_button.click()
        sleep(5)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(3)
        search_icon = self.driver.find_element_by_id("com.dukaan.app:id/search")
        search_icon.click()
        sleep(1)
        search_textbox = self.driver.find_element_by_id("com.dukaan.app:id/search_src_text")
        search_textbox.send_keys("3060659")
        sleep(5)
        order_select = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Details")')
        order_select.click()
        sleep(2)
        order_details_title = self.driver.find_element_by_id("com.dukaan.app:id/toolBarTitleTV")
        order_id_in_order_details_page = order_details_title.text
        self.assertEqual("Order #3060659", order_id_in_order_details_page)

    def test_mobile_number_matching(self):
        phone_number = "7012799237"
        self.driver.launch_app()
        sleep(2)
        get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        get_started_button.click()
        sleep(1)
        continue_with_email_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        continue_with_email_button.click()
        sleep(1)
        email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
        email_address_textbox.send_keys("cojeret739@kuruapp.com")
        sleep(1)
        continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        continue_button.click()
        sleep(2)
        password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
        password_textbox.send_keys("dukaanauto")
        sleep(2)
        enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        enter_password_button.click()
        sleep(5)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(3)
        search_icon = self.driver.find_element_by_id("com.dukaan.app:id/search")
        search_icon.click()
        sleep(1)
        search_textbox = self.driver.find_element_by_id("com.dukaan.app:id/search_src_text")
        search_textbox.send_keys(phone_number)
        sleep(2)
        order_select = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Details")')
        order_select.click()
        sleep(1)
        phone_number_in_order_details = self.driver.find_element_by_id("com.dukaan.app:id/mobileTV")
        self.assertEqual(phone_number, phone_number_in_order_details.text)

    def test_name_matching(self):
        name = "Test"
        self.driver.launch_app()
        sleep(2)
        get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        get_started_button.click()
        sleep(1)
        continue_with_email_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        continue_with_email_button.click()
        sleep(1)
        email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
        email_address_textbox.send_keys("cojeret739@kuruapp.com")
        sleep(1)
        continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        continue_button.click()
        sleep(2)
        password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
        password_textbox.send_keys("dukaanauto")
        sleep(2)
        enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        enter_password_button.click()
        sleep(5)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(3)
        search_icon = self.driver.find_element_by_id("com.dukaan.app:id/search")
        search_icon.click()
        sleep(1)
        search_textbox = self.driver.find_element_by_id("com.dukaan.app:id/search_src_text")
        search_textbox.send_keys(name)
        sleep(1)
        order_select = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Details")')
        order_select.click()
        sleep(10)
        name_in_order_details = self.driver.find_element_by_id("com.dukaan.app:id/nameTV")
        self.assertEqual(name, name_in_order_details.text)

    # def test__search_invalid_order_id(self):
    #     self.driver.launch_app()
    #     sleep(2)
    #     get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
    #     get_started_button.click()
    #     sleep(1)
    #     continue_with_email_button = self.driver.find_element_by_android_uiautomator(
    #         'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
    #     continue_with_email_button.click()
    #     sleep(1)
    #     email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
    #     email_address_textbox.send_keys("cojeret739@kuruapp.com")
    #     sleep(1)
    #     continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
    #     continue_button.click()
    #     sleep(2)
    #     password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
    #     password_textbox.send_keys("dukaanauto")
    #     sleep(2)
    #     enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
    #     enter_password_button.click()
    #     sleep(4)
    #     orders_icon = self.driver.find_element_by_android_uiautomator(
    #         'new UiSelector().className("android.widget.TextView").text("Orders")')
    #     orders_icon.click()
    #     sleep(3)
    #     search_icon = self.driver.find_element_by_id("com.dukaan.app:id/search")
    #     search_icon.click()
    #     sleep(1)
    #     search_textbox = self.driver.find_element_by_id("com.dukaan.app:id/search_src_text")
    #     search_textbox.send_keys("1232345678")
    #     sleep(1)
    #     self.driver.hide_keyboard()
    #     sleep(1)
    #     assert self.driver.find_element_by_android_uiautomator(
    #         'new UiSelector().className("android.widget.TextView").text("No orders found.")')

    # def test_search_invalid_mobile_number(self):
    #     self.driver.launch_app()
    #     sleep(2)
    #     get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
    #     get_started_button.click()
    #     sleep(1)
    #     continue_with_email_button = self.driver.find_element_by_android_uiautomator(
    #         'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
    #     continue_with_email_button.click()
    #     sleep(1)
    #     email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
    #     email_address_textbox.send_keys("cojeret739@kuruapp.com")
    #     sleep(1)
    #     continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
    #     continue_button.click()
    #     sleep(2)
    #     password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
    #     password_textbox.send_keys("dukaanauto")
    #     sleep(2)
    #     enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
    #     enter_password_button.click()
    #     sleep(4)
    #     orders_icon = self.driver.find_element_by_android_uiautomator(
    #         'new UiSelector().className("android.widget.TextView").text("Orders")')
    #     orders_icon.click()
    #     sleep(3)
    #     search_icon = self.driver.find_element_by_id("com.dukaan.app:id/search")
    #     search_icon.click()
    #     sleep(1)
    #     search_textbox = self.driver.find_element_by_id("com.dukaan.app:id/search_src_text")
    #     search_textbox.send_keys("8289850930")
    #     sleep(1)
    #     self.driver.hide_keyboard()
    #     sleep(1)
    #     assert self.driver.find_element_by_android_uiautomator(
    #         'new UiSelector().className("android.widget.TextView").text("No orders found.")')

    #def test_search_invalid_name(self):
    # self.driver.launch_app()
        #sleep(2)
        #get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        #get_started_button.click()
        #sleep(1)
        #continue_with_email_button = self.driver.find_element_by_android_uiautomator(
         #   'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        #continue_with_email_button.click()
        #sleep(1)
       # email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
       # email_address_textbox.send_keys("cojeret739@kuruapp.com")
       # sleep(1)
       # continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
       # continue_button.click()
       # sleep(2)
       # password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
       # password_textbox.send_keys("dukaanauto")
       # sleep(2)
       # enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
       # enter_password_button.click()
       # sleep(4)
       # orders_icon = self.driver.find_element_by_android_uiautomator(
       #     'new UiSelector().className("android.widget.TextView").text("Orders")')
       # orders_icon.click()
       # sleep(3)
       # search_icon = self.driver.find_element_by_id("com.dukaan.app:id/search")
       # search_icon.click()
       # sleep(1)
       # search_textbox = self.driver.find_element_by_id("com.dukaan.app:id/search_src_text")
       # search_textbox.send_keys("Invalid")
       # sleep(3)
       # self.driver.hide_keyboard()
        #sleep(3)
        #close_ad = self.driver.find_element_by_id("com.dukaan.app:id/ivClose")
        #close_ad.click()
        #sleep(2)
        #assert self.driver.find_element_by_android_uiautomator(
           # 'new UiSelector().className("android.widget.TextView").text("No orders found.")')

    def test_order_an_item_from_buyer_side(self):
        self.driver.launch_app()
        sleep(2)
        get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        get_started_button.click()
        sleep(1)
        continue_with_email_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        continue_with_email_button.click()
        sleep(1)
        email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
        email_address_textbox.send_keys("cojeret739@kuruapp.com")
        sleep(1)
        continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        continue_button.click()
        sleep(2)
        password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
        password_textbox.send_keys("dukaanauto")
        sleep(2)
        enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        enter_password_button.click()
        sleep(5)
        store_link = self.driver.find_element_by_id("com.dukaan.app:id/store_link_tv")
        store_link.click()
        sleep(5)
        product_name_in_buyer_side = self.driver.find_element_by_xpath('//android.view.View[@content-desc="Sauce per piece ₹22 Sauce ADD BUY 2 GET 1"]/android.widget.TextView[1]')
        buyer_side_name = product_name_in_buyer_side.text
        add_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("ADD")')
        add_button.click()
        sleep(5)
        bag_icon = self.driver.find_element_by_xpath(
            '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[3]/android.widget.Button[3]')
        bag_icon.click()
        sleep(7)
        continue_button_buyer = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("Continue")')
        continue_button_buyer.click()
        sleep(2)
        login_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.view.View").text("Already a user? Log in here")')
        login_button.click()
        sleep(1)
        autofill_mobile = self.driver.find_element_by_id("android:id/text1")
        autofill_mobile.click()
        sleep(1)
        mobile_number_textbox = self.driver.find_element_by_xpath(
            '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.app.Dialog/android.view.View/android.view.View[2]/android.view.View/android.view.View[2]/android.widget.EditText')
        mobile_number_textbox.send_keys("")
        sleep(1)
        mobile_number_textbox.send_keys("8047187134")
        send_otp_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("Send OTP")')
        send_otp_button.click()
        sleep(2)
        otp_textbox = self.driver.find_element_by_xpath(
            '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.app.Dialog/android.view.View/android.view.View[2]/android.view.View/android.widget.EditText')
        otp_textbox.send_keys("723573")
        sleep(8)
        continue_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("Continue")')
        continue_button.click()
        sleep(3)
        cash_on_delivery_radio = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Cash on Delivery")')
        cash_on_delivery_radio.click()
        sleep(2)
        place_order_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("Place order")')
        place_order_button.click()
        sleep(2)
        back_button = self.driver.find_element_by_xpath('//android.widget.ImageView[@content-desc="Back"]')
        back_button.click()
        sleep(4)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(2)
        order_select = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Pending")')
        order_select.click()
        sleep(3)
        item_name_in_order_details_page = self.driver.find_element_by_id("com.dukaan.app:id/itemTitleTV")
        sleep(1)
        self.assertEqual(buyer_side_name + "  ", item_name_in_order_details_page.text)

    def test_edit_order_confirmation_from_buyer(self):
        self.driver.launch_app()
        sleep(2)
        get_started_button = self.driver.find_element_by_id("com.dukaan.app:id/get_started")
        get_started_button.click()
        sleep(1)
        continue_with_email_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Continue with Email")')
        continue_with_email_button.click()
        sleep(1)
        email_address_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_input")
        email_address_textbox.send_keys("cojeret739@kuruapp.com")
        sleep(1)
        continue_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        continue_button.click()
        sleep(2)
        password_textbox = self.driver.find_element_by_id("com.dukaan.app:id/et_password")
        password_textbox.send_keys("dukaanauto")
        sleep(2)
        enter_password_button = self.driver.find_element_by_id("com.dukaan.app:id/btn_continue")
        enter_password_button.click()
        sleep(5)
        store_link = self.driver.find_element_by_id("com.dukaan.app:id/store_link_tv")
        store_link.click()
        sleep(5)
        add_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("ADD")')
        add_button.click()
        sleep(5)
        bag_icon = self.driver.find_element_by_xpath(
            '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[3]/android.widget.Button[3]')
        bag_icon.click()
        sleep(7)
        continue_button_buyer = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("Continue")')
        continue_button_buyer.click()
        sleep(2)
        login_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.view.View").text("Already a user? Log in here")')
        login_button.click()
        sleep(1)
        autofill_mobile = self.driver.find_element_by_id("android:id/text1")
        autofill_mobile.click()
        sleep(1)
        mobile_number_textbox = self.driver.find_element_by_xpath(
            '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.app.Dialog/android.view.View/android.view.View[2]/android.view.View/android.view.View[2]/android.widget.EditText')
        mobile_number_textbox.send_keys("")
        sleep(1)
        mobile_number_textbox.send_keys("8047187134")
        send_otp_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("Send OTP")')
        send_otp_button.click()
        sleep(2)
        otp_textbox = self.driver.find_element_by_xpath(
            '/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.app.Dialog/android.view.View/android.view.View[2]/android.view.View/android.widget.EditText')
        otp_textbox.send_keys("723573")
        sleep(8)
        continue_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("Continue")')
        continue_button.click()
        sleep(3)
        cash_on_delivery_radio = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Cash on Delivery")')
        cash_on_delivery_radio.click()
        sleep(2)
        place_order_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("Place order")')
        place_order_button.click()
        sleep(2)
        back_button = self.driver.find_element_by_xpath('//android.widget.ImageView[@content-desc="Back"]')
        back_button.click()
        sleep(4)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(2)
        order_select = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Pending")')
        order_select.click()
        sleep(3)
        edit_order_button = self.driver.find_element_by_id("com.dukaan.app:id/editOrderTV")
        edit_order_button.click()
        sleep(2)
        edit_fee_button = self.driver.find_element_by_id("com.dukaan.app:id/editFeeTV")
        edit_fee_button.click()
        sleep(1)
        delivery_fee_textbox = self.driver.find_element_by_id("com.dukaan.app:id/deliveryPriceET")
        delivery_fee_textbox.send_keys("100")
        change_button = self.driver.find_element_by_id("com.dukaan.app:id/confirmButton")
        change_button.click()
        sleep(1)
        request_confirmation_button = self.driver.find_element_by_id("com.dukaan.app:id/requestConfirmationButton")
        request_confirmation_button.click()
        sleep(4)
        got_it_button = self.driver.find_element_by_id("com.dukaan.app:id/closeButton")
        got_it_button.click()
        sleep(2)
        assert self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Waiting for the customer confirmation")')
        assert self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Modified")')
        back_button = self.driver.find_element_by_id("com.dukaan.app:id/backButton")
        back_button.click()
        sleep(2)
        navigate_to_home = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Home")')
        navigate_to_home.click()
        sleep(1)
        store_link = self.driver.find_element_by_id("com.dukaan.app:id/store_link_tv")
        store_link.click()
        sleep(3)
        account_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("Account")')
        account_icon.click()
        sleep(4)
        my_orders = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("My orders")')
        my_orders.click()
        sleep(2)
        order_select = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Modified")')
        order_select.click()
        sleep(3)
        view_changes_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("View changes")')
        view_changes_button.click()
        sleep(3)
        accept_button = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.Button").text("Accept changes")')
        accept_button.click()
        sleep(3)
        back_button = self.driver.find_element_by_xpath('//android.widget.ImageView[@content-desc="Back"]')
        back_button.click()
        sleep(2)
        orders_icon = self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Orders")')
        orders_icon.click()
        sleep(2)
        assert self.driver.find_element_by_android_uiautomator(
            'new UiSelector().className("android.widget.TextView").text("Pending")')

    def tearDown(self):
        self.driver.quit()


if '__main__' == __name__:
    unittest.main()
