import unittest

from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy
from appium.webdriver.common.touch_action import TouchAction
import unittest
from appium import webdriver
import pytest
from time import sleep
from selenium.webdriver.support import expected_conditions as EC
import pytest

import random

from selenium.webdriver.support.wait import WebDriverWait

from AppiumFrameWork1.tests.test_homepage import logger
from AppiumFrameWork1.pages.LoginPage import LoginPage

name = ['Delta', 'Alpha', 'Hari', 'Rijaz', 'KJ', 'Abhilash', 'Platina', 'KTM', 'Cars', 'Bikes', 'Soul', 'Spark']


class PluginPage(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Remote(command_executor="http://127.0.0.1:4723/wd/hub",
                                       desired_capabilities=
                                       {
                                           "platformName": "Android",
                                           "platformVersion": "9",
                                           "deviceName": "emulator-5554",
                                           "automationName": "uiautomator2",
                                           "app": "C:/Users/clinton/Downloads/app-prod-debug.apk",
                                           "newCommandTimeout": 600,
                                           "launchTimeout": "90000",
                                           "adbExecTimeout": "30000"
                                       })

    def test_01privy_ecommerce_marketing(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        privy_ecommerce_marketing = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginTitleTV")))
        privy_ecommerce_marketing.click()
        sleep(3)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(3)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(3)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        sleep(2)
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        free_trail_click = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Does Privy have a free trial?")')))
        free_trail_click.click()
        free_trail_click.click()
        growing_price_work = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("How does Privy Growth pricing work?")')))
        growing_price_work.click()
        growing_price_work.click()
        signup_free_plan = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("How do I sign up for the free plan?")')))
        signup_free_plan.click()
        signup_free_plan.click()
        privacy_logo = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("I am on the free plan, how do I remove the Privy logo?")')))
        privacy_logo.click()
        privacy_logo.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_02privyecommercemarketing_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        privy_ecommerce_marketing = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginTitleTV")))
        privy_ecommerce_marketing.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionButton")))
        install_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')))

    def test_03privyecommercemarketing_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        privy_ecommerce_marketing = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginTitleTV")))
        privy_ecommerce_marketing.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text(	"Plugin Settings")')))
        plugin_setting.click()
        siteid_textbox = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText")))
        siteid_textbox.click()
        siteid_textbox.send_keys("12345678")
        update_siteid = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.Button").text("Update")')))
        update_siteid.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Privy is successfully updated.")')))

    def test_04privyecommercemarketing_uninstall_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        privy_ecommerce_marketing = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginTitleTV")))
        privy_ecommerce_marketing.click()
        sleep(2)
        self.driver.swipe(518, 1989, 578, 322, 500)
        sleep(2)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR,  'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))

    def test_05intercom_live_chat(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        intercom_live_chat = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("Intercom Live Chat")')))
        intercom_live_chat.click()
        sleep(2)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        sleep(2)
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        what_is_intercom = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("What is Intercom?")')))
        what_is_intercom.click()
        what_is_intercom.click()
        benefit_intercom = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("What are the benefits of using Intercom?")')))
        benefit_intercom.click()
        benefit_intercom.click()
        intercom_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("How to install the Intercom plugin?")')))
        intercom_plugin.click()
        intercom_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_06intercomelivechat_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        intercom_live_chat = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Intercom Live Chat")')))
        intercom_live_chat.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Install Plugin")')))
        install_plugin.click()
        assert self.driver.find_element(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')

    def test_07intercomelivechat_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        intercom_live_chat = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Intercom Live Chat")')))
        intercom_live_chat.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,  'new UiSelector().className("android.widget.TextView").text("Plugin Settings")')))
        plugin_setting.click()
        appid_textbox = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText")))
        appid_textbox.click()
        appid_textbox.send_keys("12345678")
        update_siteid = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.Button").text("Update")')))
        update_siteid.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("Intercom is successfully updated.")')))

    def test_08intercomlivchat_uninstall(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        intercom_live_chat = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Intercom Live Chat")')))
        intercom_live_chat.click()
        sleep(2)
        self.driver.swipe(518, 1989, 578, 322, 500)
        sleep(2)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))

    def test_09google_analytics(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        google_analytics = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Analytics")')))
        google_analytics.click()
        sleep(2)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        sleep(2)
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        what_is_google_analytics = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("What is Google Analytics?")')))
        what_is_google_analytics.click()
        what_is_google_analytics.click()
        benefit_google_analytics = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("What are the benefits of Google Analytics?")')))
        benefit_google_analytics.click()
        benefit_google_analytics.click()
        google_analytics_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("How to install the Google Analytics plugin?")')))
        google_analytics_plugin.click()
        google_analytics_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_10googleanalytics_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        google_analytics = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Analytics")')))
        google_analytics.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("Install Plugin")')))
        install_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')))

    def test_11googleanalytics_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        google_analytics = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Analytics")')))
        google_analytics.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Settings")')))
        plugin_setting.click()
        analytics_propertyid_textbox = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText")))
        analytics_propertyid_textbox.click()
        analytics_propertyid_textbox.send_keys("12345678")
        sleep(2)
        self.driver.swipe(527,1238,562,777,500)
        sleep(2)
        connect_button = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.Button").text("Connect")')))
        connect_button.click()
        assert WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("Google Analytics is successfully updated.")')))

    def test_12googleanalytics_uninstall(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        google_analytics = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Analytics")')))
        google_analytics.click()
        self.driver.swipe(518, 1989, 578, 322, 500)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))

    def test_13facebook_pixel(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(2)
        self.driver.swipe(527, 1999, 534, 1320, 500)
        sleep(2)
        facebook_pixel = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Facebook Pixel")')))
        facebook_pixel.click()
        sleep(2)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        sleep(2)
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        sleep(1)
        what_is_facebook_pixel = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("What is Facebook Pixel?")')))
        what_is_facebook_pixel.click()
        what_is_facebook_pixel.click()
        standard_and_custom_event = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("What are standard and custom events?")')))
        standard_and_custom_event.click()
        standard_and_custom_event.click()
        pixel_to_my_online_store = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("How to install Facebook Pixel to my online store?")')))
        pixel_to_my_online_store.click()
        pixel_to_my_online_store.click()
        remove_the_facebook_pixel = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("How to change or remove the Facebook Pixel?")')))
        remove_the_facebook_pixel.click()
        remove_the_facebook_pixel.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_14facebookpixel_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(2)
        self.driver.swipe(527, 1999, 534, 1320, 500)
        sleep(2)
        facebook_pixel = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Facebook Pixel")')))
        facebook_pixel.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,  'new UiSelector().className("android.widget.TextView").text("Install Plugin")')))
        install_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')))

    def test_15facebookpixel_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        facebook_pixel = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Facebook Pixel")')))
        facebook_pixel.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Settings")')))
        plugin_setting.click()
        pixel_id_textbox = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText")))
        pixel_id_textbox.click()
        pixel_id_textbox.send_keys("12345678")
        sleep(2)
        self.driver.swipe(527, 1238, 562, 777, 500)
        sleep(2)
        update_button = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.Button").text("Update")')))
        update_button.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("Facebook Analytics is successfully updated.")')))

    def test_16facebookpixel_uninstall(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        facebook_pixel = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Facebook Pixel")')))
        facebook_pixel.click()
        sleep(2)
        self.driver.swipe(518, 1989, 578, 322, 500)
        sleep(2)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))

    def test_17adwordsconversiontracking_pixel(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(3)
        self.driver.swipe(527, 1999, 534, 1320, 500)
        sleep(2)
        adwords_conversion_tracking = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Adwords Conversion Tracking")')))
        adwords_conversion_tracking.click()
        sleep(2)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,
                                                                                              'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        track_the_conversion_on = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,   'new UiSelector().className("android.widget.TextView").text("Which networks I can track the conversions on?")')))
        track_the_conversion_on.click()
        track_the_conversion_on.click()
        plugin_free_to_use = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Is this plugin free to use?")')))
        plugin_free_to_use.click()
        plugin_free_to_use.click()
        google_adwords_account_to_use_this = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Do I need Google Adwords account to use this?")')))
        google_adwords_account_to_use_this.click()
        google_adwords_account_to_use_this.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_18adwordsconversiontracking_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(2)
        self.driver.swipe(527, 1999, 534, 1320, 500)
        sleep(2)
        adwords_conversion_tracking = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Adwords Conversion Tracking")')))
        adwords_conversion_tracking.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Install Plugin")')))
        install_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')))

    def test_19adwordsconversiontracking_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        adwords_conversion_tracking = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Adwords Conversion Tracking")')))
        adwords_conversion_tracking.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("Plugin Settings")')))
        plugin_setting.click()
        conversion_id_textbox = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH,"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText[1]")))
        conversion_id_textbox.click()
        conversion_id_textbox.send_keys("12345678")
        sleep(2)
        self.driver.swipe(524, 1232, 521, 1635, 500)
        sleep(2)
        conversion_label_id_textbox = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText[2]")))
        conversion_label_id_textbox.click()
        sleep(2)
        self.driver.swipe(524, 1232, 521, 1635, 500)
        sleep(2)
        conversion_label_id_textbox.send_keys("123456789")
        sleep(2)
        self.driver.swipe(524, 1232, 521, 1635, 500)
        sleep(2)
        connect_button = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.Button").text("Connect")')))
        connect_button.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Adwords Conversion Tracking is successfully updated.")')))

    def test_20adwordsconversiontracking_uninstall(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        adwords_conversion_tracking = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Adwords Conversion Tracking")')))
        adwords_conversion_tracking.click()
        sleep(2)
        self.driver.swipe(518, 1989, 578, 322, 500)
        sleep(2)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))

    def test_29google_merchant_center(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(3)
        self.driver.swipe(543, 2005, 543, 430, 500)
        sleep(2)
        google_merchant_center = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Merchant Center")')))
        google_merchant_center.click()
        sleep(2)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,
                                                                                              'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        benefit_do_i_get_from_this = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("What benefit do I get from this?")')))
        benefit_do_i_get_from_this.click()
        benefit_do_i_get_from_this.click()
        plugin_free_to_use = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Is this plugin free to use?")')))
        plugin_free_to_use.click()
        plugin_free_to_use.click()
        gmc_account_to_use_this = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Do I need a GMC account to use this?")')))
        gmc_account_to_use_this.click()
        gmc_account_to_use_this.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_30googlemerchantcenter_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(2)
        self.driver.swipe(543, 2005, 543, 750, 500)
        sleep(2)
        google_merchant_center = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Merchant Center")')))
        google_merchant_center.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Install Plugin")')))
        install_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')))

    def test_31googlemerchantcenter_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        google_merchant_center = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Merchant Center")')))
        google_merchant_center.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("Plugin Settings")')))
        plugin_setting.click()
        gmc_verfication_code = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH,"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText")))
        gmc_verfication_code.click()
        gmc_verfication_code.send_keys("12345678")
        sleep(2)
        self.driver.swipe(518,1225,537,900,400)
        connect_button = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.Button").text("Connect")')))
        connect_button.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Merchant Center is successfully updated.")')))

    def test_32googlemerchantcenter_uninstall(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        google_merchant_center = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Merchant Center")')))
        google_merchant_center.click()
        sleep(2)
        self.driver.swipe(518, 1989, 578, 322, 500)
        sleep(2)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))

    def test_33google_search_console(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(3)
        self.driver.swipe(543, 2005, 543, 430, 500)
        sleep(2)
        google_search_console = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Search Console")')))
        google_search_console.click()
        sleep(2)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,
                                                                                              'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        benefit_do_i_get_from_this = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("What benefit do I get from this?")')))
        benefit_do_i_get_from_this.click()
        benefit_do_i_get_from_this.click()
        plugin_free_to_use = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Is this plugin free to use?")')))
        plugin_free_to_use.click()
        plugin_free_to_use.click()
        gsc_account_to_use_this = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Do I need a Google Search Console account to use this?")')))
        gsc_account_to_use_this.click()
        gsc_account_to_use_this.click()
        use_google_search_console = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Who should use Google Search Console?")')))
        use_google_search_console.click()
        use_google_search_console.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_34googlesearchconsole_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(2)
        self.driver.swipe(543, 2005, 543, 430, 500)
        sleep(2)
        google_search_console = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Search Console")')))
        google_search_console.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Install Plugin")')))
        install_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')))

    def test_35googlesearchconsole_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        google_search_console = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Search Console")')))
        google_search_console.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("Plugin Settings")')))
        plugin_setting.click()
        gsc_verfication_code = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH,"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText")))
        gsc_verfication_code.click()
        gsc_verfication_code.send_keys("12345678")
        self.driver.swipe(518, 1225, 537, 714, 400)
        connect_button = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.Button").text("Connect")')))
        connect_button.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Search Console is successfully updated.")')))

    def test_36googlesearchconsole_uninstall(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        google_search_console = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Google Search Console")')))
        google_search_console.click()
        sleep(2)
        self.driver.swipe(518, 1989, 578, 322, 500)
        sleep(2)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))

    def test_37facebook_domain_verification(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(3)
        self.driver.swipe(543, 2005, 543, 430, 500)
        sleep(2)
        facebook_domain_verification = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Facebook Domain Verification")')))
        facebook_domain_verification.click()
        sleep(2)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,
                                                                                              'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        benefit_do_i_get_from_this = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("What benefit do I get from this?")')))
        benefit_do_i_get_from_this.click()
        benefit_do_i_get_from_this.click()
        plugin_free_to_use = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Is this plugin free to use?")')))
        plugin_free_to_use.click()
        plugin_free_to_use.click()
        fbm_account_to_use_this = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Do I need a Facebook Business Manager account to use this?")')))
        fbm_account_to_use_this.click()
        fbm_account_to_use_this.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_38facebookdomainverification_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(2)
        self.driver.swipe(543, 2005, 543, 430, 500)
        sleep(2)
        facebook_domain_verification = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Facebook Domain Verification")')))
        facebook_domain_verification.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Install Plugin")')))
        install_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')))

    def test_39facebookdomainverification_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        facebook_domain_verification = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Facebook Domain Verification")')))
        facebook_domain_verification.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR,'new UiSelector().className("android.widget.TextView").text("Plugin Settings")')))
        plugin_setting.click()
        fsc_verfication_code = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH,"/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText")))
        fsc_verfication_code.click()
        fsc_verfication_code.send_keys("12345678")
        self.driver.swipe(518, 1225, 537, 714, 400)
        connect_button = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.Button").text("Connect")')))
        connect_button.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Facebook Domain Verification is successfully updated.")')))

    def test_40facebookdomainverification_uninstall(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        facebook_domain_verification = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Facebook Domain Verification")')))
        facebook_domain_verification.click()
        sleep(2)
        self.driver.swipe(518, 1989, 578, 322, 500)
        sleep(2)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))

    def test_41fomo(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(3)
        self.driver.swipe(543, 2005, 543, 300, 500)
        sleep(2)
        fomo = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Fomo")')))
        fomo.click()
        sleep(2)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        fomo_have_free_trail = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Does Fomo have a free trial?")')))
        fomo_have_free_trail.click()
        fomo_have_free_trail.click()
        fomo_working_on_my_site = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Do I need a lot of purchases to see Fomo working on my site?")')))
        fomo_working_on_my_site.click()
        fomo_working_on_my_site.click()
        my_store_order_history = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("How can I show older orders from my store orders history?")')))
        my_store_order_history.click()
        my_store_order_history.click()
        product_sales_to_my_dukaan_store = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("How does Fomo automatically sync product sales to my Dukaan store?")')))
        product_sales_to_my_dukaan_store.click()
        product_sales_to_my_dukaan_store.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_42fomo_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(2)
        self.driver.swipe(543, 2005, 543, 300, 400)
        sleep(2)
        fomo = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Fomo")')))
        fomo.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Install Plugin")')))
        install_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')))

    def test_43fomo_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        fomo = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Fomo")')))
        fomo.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Settings")')))
        plugin_setting.click()
        auth_token_textbox = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText[1]")))
        auth_token_textbox.click()
        auth_token_textbox.send_keys("12345678")
        sleep(2)
        self.driver.swipe(524, 1232, 521, 1635, 500)
        sleep(2)
        embed_snippet_textbox = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText[2]")))
        embed_snippet_textbox.click()
        sleep(2)
        self.driver.swipe(524, 1232, 521, 1635, 500)
        sleep(2)
        embed_snippet_textbox.send_keys("123456789")
        sleep(2)
        self.driver.swipe(524, 1232, 521, 1635, 500)
        sleep(2)
        update_button = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.Button").text("Update")')))
        update_button.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Fomo is successfully updated.")')))



    def test_44fomo_uninstall(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        fomo = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Fomo")')))
        fomo.click()
        sleep(2)
        self.driver.swipe(518, 1989, 578, 300, 500)
        sleep(2)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))


    def test_45Optinmonster(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(3)
        self.driver.swipe(543, 2005, 543, 300, 500)
        sleep(2)
        optin_monster = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Optinmonster")')))
        optin_monster.click()
        sleep(2)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        use_optin_monster = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Who should use OptinMonster?")')))
        use_optin_monster.click()
        use_optin_monster.click()
        skill_to_use_optinmonster= WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Who should use OptinMonster?")')))
        skill_to_use_optinmonster.click()
        skill_to_use_optinmonster.click()
        free_to_use = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Is this free to use?")')))
        free_to_use.click()
        free_to_use.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_46optinmonster_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(2)
        self.driver.swipe(543, 2005, 543, 290, 500)
        sleep(2)
        optin_monster = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Optinmonster")')))
        optin_monster.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Install Plugin")')))
        install_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')))

    def test_47optinmonster_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        optin_monster = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Optinmonster")')))
        optin_monster.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Settings")')))
        plugin_setting.click()
        global_embeded_code = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText")))
        global_embeded_code.click()
        global_embeded_code.send_keys("123456789")
        sleep(2)
        self.driver.swipe(521, 1206, 534, 527, 500)
        sleep(2)
        update_button = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.Button").text("Update")')))
        update_button.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Optinmonster is successfully updated.")')))

    def test_48optinmonster_uninstall(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        optin_monster = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Optinmonster")')))
        optin_monster.click()
        sleep(2)
        self.driver.swipe(518, 1989, 578, 322, 500)
        sleep(2)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))

    def test_49clarity_by_microsoft(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(3)
        self.driver.swipe(543, 2005, 543, 200, 500)
        sleep(2)
        clarity_by_microsoft = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Clarity by Microsoft")')))
        clarity_by_microsoft.click()
        sleep(2)
        self.driver.swipe(505, 1999, 568, 287, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        installation_guide = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Installation Guide")')))
        installation_guide.click()
        self.driver.swipe(524, 1993, 534, 887, 500)
        sleep(2)
        self.driver.swipe(518, 249, 543, 1964, 500)
        sleep(2)
        faq = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("FAQ")')))
        faq.click()
        why_should_i_clarity = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Why should I use Clarity?")')))
        why_should_i_clarity.click()
        why_should_i_clarity.click()
        clarity_cost = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("How much does Clarity cost?")')))
        clarity_cost.click()
        clarity_cost.click()
        reduce_my_site_performance = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("	Will Clarity reduce my sites performance?")')))
        reduce_my_site_performance.click()
        reduce_my_site_performance.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin details")')))

    def test_50claritybymicrosoft_install_plugin(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        sleep(2)
        self.driver.swipe(543, 2005, 543, 290, 500)
        sleep(2)
        clarity_by_microsoft = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Clarity by Microsoft")')))
        clarity_by_microsoft.click()
        install_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Install Plugin")')))
        install_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Activated!")')))

    def test_51claritybymicrosoft_pluginsetting(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        clarity_by_microsoft = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Clarity by Microsoft")')))
        clarity_by_microsoft.click()
        plugin_setting = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Settings")')))
        plugin_setting.click()
        clarity_tracking_code = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[3]/android.widget.EditText")))
        clarity_tracking_code.click()
        clarity_tracking_code.send_keys("123456789")
        update_button = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.Button").text("Update")')))
        update_button.click()
        assert WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Clarity is successfully updated.")')))

    def test_52claritybymicrosoft_uninstall(self):
        self.cf = LoginPage(self.driver)
        self.cf.logincall()
        manage_icon = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Manage")')))
        manage_icon.click()
        dukaan_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.XPATH, "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[5]/android.widget.FrameLayout/android.widget.LinearLayout")))
        dukaan_plugin.click()
        clarity_by_microsoft = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Clarity by Microsoft")')))
        clarity_by_microsoft.click()
        sleep(2)
        self.driver.swipe(518, 1989, 578, 322, 500)
        sleep(2)
        unistall_plugin = WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ID, "com.dukaan.app:id/pluginActionTV")))
        unistall_plugin.click()
        assert WebDriverWait(self.driver, 15).until(EC.element_to_be_clickable((AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().className("android.widget.TextView").text("Plugin Deactivated!")')))


def tearDown(self):
    self.driver.quit()


if '__main__' == __name__:
    unittest.main()
